import os
import requests
from dotenv import load_dotenv

#Env Configuration, SAP keys. Get from the .env file
load_dotenv()

SAP_BASE_URL = os.getenv("SAP_BYD_BASE_URL") or ""
SAP_USERNAME = os.getenv("SAP_BYD_USERNAME") or ""
SAP_PASSWORD = os.getenv("SAP_BYD_PASSWORD") or ""

AUTH = (SAP_USERNAME, SAP_PASSWORD)

QUERY_ENDPOINT = f"{SAP_BASE_URL}/sap/byd/odata/ana_businessanalytics_analytics.svc/RPBUPCSD_Q0001QueryResults"
ADDRESS_QUERY_ENDPOINT = f"{SAP_BASE_URL}/sap/byd/odata/ana_businessanalytics_analytics.svc/RPZ354E43506089F046ADF360QueryResults"

# Technical field names as generated by the SAP ByDesign analytics query.
# Used verbatim in $select since that's what the OData service expects and
# returns as JSON keys.
BP_ADDRESS_FIELDS = [
    "C1BP_UUIDsADDR_ST_SUFFIX",
    "C1P128W48BOVUX63AP5MFZDROB7",
    "C1BP_UUIDsADDR_ST_PREFIX",
    "TBP_UUID",
    "T1BP_UUIDsBP_INT_ID",
    "T1RCCB4ZHM0J17U2RATDRI15CCF",
    "T1LLUDMAW7MCWPWTP6X2LQ6XG0Q",
    "C1RCCB4ZHM0J17U2RATDRI15CCF",
    "CBP_UUID",
    "C1BP_UUIDsBP_INT_ID",
    "C1BP_UUIDsFRMTD_PSTL_ADDR",
    "CFRMTD_PSTL_ADDR",
    "C1LLUDMAW7MCWPWTP6X2LQ6XG0Q",
    "C1HHCW1VDBF5M2VKELP67M5K0IC",
    "T1HHCW1VDBF5M2VKELP67M5K0IC",
]

# Maps each technical field name to the human-readable field name from the
# query's characteristic list, so the DB can use readable column names
# while still selecting the exact technical fields from OData.
BP_ADDRESS_FIELD_MAP = {
    "C1BP_UUIDsADDR_ST_SUFFIX": "address_line_4_id",
    "C1P128W48BOVUX63AP5MFZDROB7": "address_line_2_id",
    "C1BP_UUIDsADDR_ST_PREFIX": "address_line_1_id",
    "TBP_UUID": "account_text",
    "T1BP_UUIDsBP_INT_ID": "account_id_text",
    "T1RCCB4ZHM0J17U2RATDRI15CCF": "outside_sales_rep_text",
    "T1LLUDMAW7MCWPWTP6X2LQ6XG0Q": "inside_sales_rep_text",
    "C1RCCB4ZHM0J17U2RATDRI15CCF": "outside_sales_rep_id",
    "CBP_UUID": "account_id",
    "C1BP_UUIDsBP_INT_ID": "account_id_id",
    "C1BP_UUIDsFRMTD_PSTL_ADDR": "bp_uuid_address_id",
    "CFRMTD_PSTL_ADDR": "address_id",
    "C1LLUDMAW7MCWPWTP6X2LQ6XG0Q": "inside_sales_rep_id",
    "C1HHCW1VDBF5M2VKELP67M5K0IC": "corporate_rep_id",
    "T1HHCW1VDBF5M2VKELP67M5K0IC": "corporate_rep_text",
}

ADDRESS_FIELDS = [
    "CBP_UUID",
    "CUUIDCOSUSAGE234D3B5D7B3580C8",
    "CADDRESSUSAGEB5C83F94C73139B4",
    "CBUILDISUSAGEF79F9903EA5C0204",
    "CCITYNASUSAGED4F7D4498A6791B9",
    "CCOUNTRSUSAGE0CD614A4BF256192",
    "TCOUNTRSUSAGE0CD614A4BF256192",
    "CCOUNTYSUSAGE5E2A2013C37CC32E",
    "CUUIDCOSUSAGE5CDC4D1AF3EB5ACD",
    "CDISTRISUSAGE97734EE251925442",
    "CURICONSUSAGEBF32248A7EAA785A",
    "CNORMALSUSAGE50A3CF338F0CCE3D",
    "CHOUSEISUSAGEF60B32918A7CA5D6",
    "CMAIN_ADDRESS_01",
    "CPOBOXDSUSAGEF5EA381BCE0ADDFE",
    "CPOBOXDSUSAGE0F4E98419BB98E16",
    "TPOBOXDSUSAGE0F4E98419BB98E16",
    "TPOBOXDSUSAGE81EB8518367BCD9A",
    "CPOBOXISUSAGE76441E1208D76109",
    "CPOBOXPSUSAGE0A96189D12DEBDEE",
    "CREGIONSUSAGE85785F9CA69E1894",
    "TREGIONSUSAGE85785F9CA69E1894",
    "CROOMIDSUSAGE4A0BB94EBE12C8F8",
    "C1BP_UUIDsSTATUS",
    "T1BP_UUIDsSTATUS",
    "CSTREETSUSAGE5099B40F7E1FD25F",
    "CSTREETSUSAGE80A48ABBFD417553",
    "CSTREETSUSAGE30324F045BB8D565",
    "CSTREETSUSAGEEAC27B13E4E7117F",
    "CSTUDIOSUSAGE2696F5EECD3BF047",
    "TTAXJURSUSAGE1B136C580FF00F34",
    "CTIMEZOSUSAGE07E0D98876093015",
    "TTIMEZOSUSAGE07E0D98876093015",
    "CURIDEFSUSAGE9A46C71FBCB67494",
]

ADDRESS_FIELD_MAP = {
    "CBP_UUID": "bp_uuid",
    "CUUIDCOSUSAGE234D3B5D7B3580C8": "address_uuid",
    "CADDRESSUSAGEB5C83F94C73139B4": "address_usage_code_id",
    "CBUILDISUSAGEF79F9903EA5C0204": "building_id",
    "CCITYNASUSAGED4F7D4498A6791B9": "city_id",
    "CCOUNTRSUSAGE0CD614A4BF256192": "country_id",
    "TCOUNTRSUSAGE0CD614A4BF256192": "country_text",
    "CCOUNTYSUSAGE5E2A2013C37CC32E": "county_id",
    "CUUIDCOSUSAGE5CDC4D1AF3EB5ACD": "customer_uuid",
    "CDISTRISUSAGE97734EE251925442": "district_id",
    "CURICONSUSAGEBF32248A7EAA785A": "email_uri_id",
    "CNORMALSUSAGE50A3CF338F0CCE3D": "email_id",
    "CHOUSEISUSAGEF60B32918A7CA5D6": "house_id",
    "CMAIN_ADDRESS_01": "main_address_id",
    "CPOBOXDSUSAGEF5EA381BCE0ADDFE": "po_box_dev_city_id",
    "CPOBOXDSUSAGE0F4E98419BB98E16": "po_box_dev_country_id",
    "TPOBOXDSUSAGE0F4E98419BB98E16": "po_box_dev_country_text",
    "TPOBOXDSUSAGE81EB8518367BCD9A": "po_box_dev_region_text",
    "CPOBOXISUSAGE76441E1208D76109": "po_box_id",
    "CPOBOXPSUSAGE0A96189D12DEBDEE": "po_box_postal_code_id",
    "CREGIONSUSAGE85785F9CA69E1894": "region_id",
    "TREGIONSUSAGE85785F9CA69E1894": "region_text",
    "CROOMIDSUSAGE4A0BB94EBE12C8F8": "room_id",
    "C1BP_UUIDsSTATUS": "status_id",
    "T1BP_UUIDsSTATUS": "status_text",
    "CSTREETSUSAGE5099B40F7E1FD25F": "street_id",
    "CSTREETSUSAGE80A48ABBFD417553": "street_postal_code_id",
    "CSTREETSUSAGE30324F045BB8D565": "street_prefix_id",
    "CSTREETSUSAGEEAC27B13E4E7117F": "street_suffix_id",
    "CSTUDIOSUSAGE2696F5EECD3BF047": "studio_address_id",
    "TTAXJURSUSAGE1B136C580FF00F34": "tax_jurisdiction_text",
    "CTIMEZOSUSAGE07E0D98876093015": "time_zone_id",
    "TTIMEZOSUSAGE07E0D98876093015": "time_zone_text",
    "CURIDEFSUSAGE9A46C71FBCB67494": "website_id",
}

PAGE_SIZE = 5000

print("✓ SAP pagination functions loaded")


def fetch_bp_addresses_page(skip=0):
    """
    Fetch a single page (PAGE_SIZE rows starting at `skip`) from the
    RPBUPCSD_Q0001QueryResults SAP ByDesign analytics query.
    This analytics service doesn't return a `d.__next` server-driven
    paging link, so pagination has to be done with $top/$skip: the
    caller keeps calling with an increasing `skip` (PAGE_SIZE at a time)
    until a page comes back shorter than PAGE_SIZE.
    """
    params = {
        "$select": ",".join(BP_ADDRESS_FIELDS),
        "$format": "json",
        "$top": PAGE_SIZE,
        "$skip": skip,
    }

    response = requests.get(
        QUERY_ENDPOINT,
        auth=AUTH,
        headers={"Accept": "application/json"},
        params=params,
    )
    response.raise_for_status()
    payload = response.json()

    data = payload.get("d", {})
    return data.get("results", [])


def fetch_addresses_page(skip=0):
    """
    Fetch a single page (PAGE_SIZE rows starting at `skip`) from the
    RPZ354E43506089F046ADF360QueryResults SAP ByDesign analytics query.
    This analytics service doesn't return a `d.__next` server-driven
    paging link, so pagination has to be done with $top/$skip: the
    caller keeps calling with an increasing `skip` (PAGE_SIZE at a time)
    until a page comes back shorter than PAGE_SIZE.
    """
    params = {
        "$select": ",".join(ADDRESS_FIELDS),
        "$format": "json",
        "$top": PAGE_SIZE,
        "$skip": skip,
    }

    response = requests.get(
        ADDRESS_QUERY_ENDPOINT,
        auth=AUTH,
        headers={"Accept": "application/json"},
        params=params,
    )
    response.raise_for_status()
    payload = response.json()

    data = payload.get("d", {})
    return data.get("results", [])
